# Generated by Django 4.1.6 on 2023-02-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_height_user_height_feet_user_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.AddField(
            model_name='user',
            name='height_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
