# Generated by Django 4.1.6 on 2023-02-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='food_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
