# Generated by Django 4.1.6 on 2023-02-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_height_profile_height_inches_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
