# Generated by Django 4.1.6 on 2023-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
