# Generated by Django 4.1.6 on 2023-03-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_item_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='score',
        ),
    ]
